### ISSUE TITLE
Enhancement: Fix week7

### ISSUE THREAD

**Issue by Sanscode1937** [AngelDTF/FNF-NewgroundsPort#10]
I fix about week7 on fnf newground port and i turn it into og engine https://github.com/Sanscode1937/OG-ENGINE
I will credit to you soon

**Comment by Cheese-Curd** [comment]
I'll compile it and run this on my machine and I'll see if it will possibly work

**Comment by Cheese-Curd** [comment]
Not trying to be rude, but have you played the Newgrounds version? You've stripped away options, removing custom inputs, removed the `Change Difficulty`, and `Practice Mode` you also broke the `blueballed` counter, also what do you mean by "fixed week 7" there doesn't seem to be anything wrong with it in the build Angel made.

**Comment by AngelWyvern** [comment]
As mentioned in a different issue, due to real life situations, I’m living in the middle of no where at the moment with literally little to no internet. Because of this, I actually have a lot of reverse engineered code still on my laptop that hasn’t been pushed to GitHub yet. Don’t worry though, this should all be resolved within a few days.
