### ISSUE TITLE
Bug Report: gfcutscene layer variable should be FlxGroup not FlxTypedGroup

### ISSUE THREAD

**Issue by Sanscode1937** [AngelDTF/FNF-NewgroundsPort#17]
gfCutsceneLayer variable should be FlxGroup
because I test da Guns cutscene and the texture atlas animation frame rate is fast af well.

**Comment by AngelWyvern** [comment]
FlxGroup is an alias for FlxTypedGroup (see image below) with type FlxBasic given instead of what I used (FlxSprite). The transpiled JS code does not show what type was given to the group, just that it is a group.
![image](https://user-images.githubusercontent.com/43016525/158464135-950ac274-bc96-4f1e-b163-6f7451f608b7.png)
Unless you have direct proof of what the variable is with something like a VOD, this won't be changing.
