### ISSUE TITLE
Enhancement: use new FlxAnimate instead of old version

### ISSUE THREAD

**Issue by Sanscode1937** [AngelDTF/FNF-NewgroundsPort#18]
use https://lib.haxe.org/p/flxanimate/ 
instead of old version

I dont think youre gonna add it.. but ok

**Comment by AngelWyvern** [comment]
Actually, I could port a lot of code over from that repo, since a decent amount of it matches up, and I did have a hell of a time reverse engineering the animate files. This'll definitely clean up a bit of the source code. Thanks for reaching out! The changes should be done by the time I push the next commit.

**Comment by AngelWyvern** [comment]
Finished porting over a lot of code from the library, thanks again btw. You'll see the changes in the next commit. I estimate at the least another 2 weeks, at the most maybe a month (give/take a few days of course) until the commit is fully done.

**Comment by AngelWyvern** [comment]
Implemented in commit 8242b12ac48a08368c9fee014a15dcea02c78dd6.
